declare module 'prismjs/components/prism-bash';
declare module 'prismjs/components/prism-batch';
declare module 'prismjs/components/prism-powershell';
declare module 'prismjs/components/prism-json';
declare module 'prismjs/components/prism-yaml';
declare module 'prismjs/components/prism-javascript';
declare module 'prismjs/components/prism-typescript';
declare module 'prismjs/components/prism-jsx';
declare module 'prismjs/components/prism-tsx';
